window.JOBS_DATA = [
  {"title":"Software developers and programmers","group":"ICT","employment":925000,"pay":6100,"education":"Bachelor or vocational+","ai":0.92,"automation":0.78,"digital":0.97,"outlook":18,"language":"english","languageLabel":"English-friendly","summary":"Coding, testing, software architecture, platform work, and AI-assisted development tasks.","rationale":"Digital workflows, code generation, and review are highly exposed to generative AI.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Data analysts and data scientists","group":"ICT","employment":135000,"pay":6400,"education":"Bachelor+","ai":0.95,"automation":0.66,"digital":0.99,"outlook":21,"language":"english","languageLabel":"English-friendly","summary":"Analytical and model-based work with very high digital-AI exposure.","rationale":"Data extraction, summarization, modeling, and presentation are strongly AI-assisted.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Office clerks and administrative staff","group":"Business support","employment":1780000,"pay":3650,"education":"Vocational","ai":0.88,"automation":0.84,"digital":0.89,"outlook":2,"language":"german","languageLabel":"German-required","summary":"Documentation, scheduling, data entry, coordination, and general back-office tasks.","rationale":"Highly structured office workflows make this group one of the most exposed to AI and automation.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Accountants, controllers, and payroll staff","group":"Finance","employment":690000,"pay":5050,"education":"Vocational or Bachelor","ai":0.86,"automation":0.8,"digital":0.87,"outlook":4,"language":"bilingual","languageLabel":"Bilingual","summary":"Structured financial processing with strong AI and automation exposure.","rationale":"Reconciliation, reporting, compliance, and routine accounting are strong AI targets.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Lawyers and legal professionals","group":"Legal","employment":184000,"pay":7800,"education":"State exam / Master","ai":0.79,"automation":0.54,"digital":0.85,"outlook":8,"language":"german","languageLabel":"German-required","summary":"Research, drafting, review and advisory work, partially exposed to digital AI.","rationale":"Legal research and document production are exposed, but judgment and responsibility keep humans central.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Teachers and education professionals","group":"Education","employment":1260000,"pay":5300,"education":"Bachelor+","ai":0.58,"automation":0.3,"digital":0.63,"outlook":14,"language":"german","languageLabel":"German-required","summary":"Lesson planning and grading are exposed, but classroom interaction reduces full automation.","rationale":"AI can assist preparation and assessment, but teaching is still highly relational.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Marketing, media, and communication specialists","group":"Creative business","employment":410000,"pay":4700,"education":"Bachelor or vocational+","ai":0.84,"automation":0.59,"digital":0.91,"outlook":6,"language":"english","languageLabel":"English-friendly","summary":"Content generation, campaign design, and analytics are strongly exposed to generative AI.","rationale":"Writing, ideation, and multi-format content production are highly exposed to generative systems.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Customer service representatives","group":"Sales and service","employment":620000,"pay":3250,"education":"Vocational","ai":0.82,"automation":0.76,"digital":0.85,"outlook":3,"language":"bilingual","languageLabel":"Bilingual","summary":"High exposure through chat, call scripting, and knowledge-base workflows.","rationale":"Support scripts, triage, and messaging are easy to augment with AI.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Retail salespersons","group":"Sales and service","employment":1530000,"pay":2800,"education":"Vocational","ai":0.41,"automation":0.48,"digital":0.39,"outlook":1,"language":"german","languageLabel":"German-required","summary":"Some exposure via scheduling, inventory, and e-commerce tools, but much work remains physical and interpersonal.","rationale":"Point-of-sale and planning systems are exposed, but face-to-face selling remains central.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Nurses and midwives","group":"Health","employment":1410000,"pay":4200,"education":"Vocational or Bachelor","ai":0.32,"automation":0.22,"digital":0.36,"outlook":19,"language":"german","languageLabel":"German-required","summary":"Clinical documentation is exposed, but bedside care remains low-exposure.","rationale":"Care work is physically and emotionally grounded, so AI mostly reduces admin burden.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Physicians","group":"Health","employment":460000,"pay":9200,"education":"University","ai":0.52,"automation":0.26,"digital":0.68,"outlook":17,"language":"german","languageLabel":"German-required","summary":"Diagnostics and paperwork are exposed while accountability and clinical judgment limit automation.","rationale":"Medical decision support is strong, but final responsibility keeps the occupation human-led.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Engineering professionals","group":"Engineering","employment":1190000,"pay":6200,"education":"Bachelor+","ai":0.71,"automation":0.46,"digital":0.78,"outlook":11,"language":"english","languageLabel":"English-friendly","summary":"Simulation, design, CAD, documentation, and optimization create substantial AI exposure.","rationale":"Technical analysis, drafting, and design work are especially amenable to AI augmentation.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Production machine operators","group":"Manufacturing","employment":970000,"pay":3400,"education":"Vocational","ai":0.29,"automation":0.69,"digital":0.24,"outlook":0,"language":"german","languageLabel":"German-required","summary":"High classic automation exposure but lower direct digital-AI exposure than office work.","rationale":"Physical plant control is more affected by robotics and automation than by generative AI.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Logistics and warehouse workers","group":"Logistics","employment":890000,"pay":3150,"education":"Vocational","ai":0.25,"automation":0.62,"digital":0.22,"outlook":5,"language":"german","languageLabel":"German-required","summary":"Routing and inventory software raise automation exposure, while physical execution limits digital AI substitution.","rationale":"Planning is exposed, but boxes still need human handling, scanning, and exception management.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Drivers and transport workers","group":"Transport","employment":830000,"pay":3050,"education":"Vocational","ai":0.18,"automation":0.58,"digital":0.12,"outlook":-1,"language":"german","languageLabel":"German-required","summary":"Platform coordination is digital, but core work remains physical and location-bound.","rationale":"Route optimization and dispatch are exposed; the core movement of goods remains harder to automate.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Construction trades workers","group":"Construction","employment":1460000,"pay":3550,"education":"Vocational","ai":0.14,"automation":0.21,"digital":0.1,"outlook":9,"language":"german","languageLabel":"German-required","summary":"Planning tools help, but execution is physical, site-specific, and low in digital AI exposure.","rationale":"The work is highly embodied and site-specific, keeping direct AI substitution low.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Cleaners and housekeeping staff","group":"Facilities","employment":990000,"pay":2450,"education":"No formal req. / vocational","ai":0.08,"automation":0.18,"digital":0.05,"outlook":2,"language":"german","languageLabel":"German-required","summary":"Very low digital-AI exposure because tasks are physical and non-screen based.","rationale":"AI has little direct impact beyond scheduling and route planning tools.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Research scientists","group":"Science","employment":230000,"pay":6700,"education":"Master / PhD","ai":0.74,"automation":0.34,"digital":0.81,"outlook":12,"language":"english","languageLabel":"English-friendly","summary":"Literature review, coding, analysis, and drafting are exposed while original inquiry remains less substitutable.","rationale":"Research workflows are deeply digital and language-heavy, making them highly AI-augmentable.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Public administration officers","group":"Government","employment":585000,"pay":4300,"education":"Vocational or Bachelor","ai":0.77,"automation":0.7,"digital":0.82,"outlook":1,"language":"german","languageLabel":"German-required","summary":"Rules-based processing and document-heavy workflows create high exposure.","rationale":"Administrative processing, form handling, and standard correspondence are classic AI use cases.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."},
  {"title":"Hospitality and food service workers","group":"Hospitality","employment":1080000,"pay":2550,"education":"Vocational / no formal req.","ai":0.16,"automation":0.27,"digital":0.12,"outlook":10,"language":"german","languageLabel":"German-required","summary":"Reservation and ordering systems digitize the edge of the job, but service remains physical.","rationale":"AI may help with booking and menu workflows, but hospitality is still strongly human-facing.","source":"Official occupation and earnings base; AI exposure modeled from occupational task structure."}
];

